spring:
  application:
    name: zuul-service

server:
  port: 9000

info:
  component: Eureka Server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8000/eureka/

zuul:
  routes:
    # BASE-SERVER BEGIN
    # oauth2-server
    authorization-manager:
      path: /api-am/**
      serviceId: authorization-manager
      sensitiveHeaders:
    authorization-service:
      path: /api-as/**
      serviceId: authorization-service
      sensitiveHeaders:

    # file-server
    file-service:
      path: /api-fs/**
      serviceId: file-service
      sensitiveHeaders:

    # ./BASE-SERVER END
    # CONSUMER-FINANCE BEGIN
    api-lmc:
      path: /api-lmc/**
      serviceId: loan-manager-core
      sensitiveHeaders:
    api-lms:
      path: /api-lms/**
      serviceId: loan-manager-service
      sensitiveHeaders:
    api-lmpmbff:
      path: /api-lmpmbff/**
      serviceId: loan-manager-pm-bff
      sensitiveHeaders:
    api-lmmobilebff:
      path: /api-lmmobilebff/**
      serviceId: loan-manager-mobile-bff
      sensitiveHeaders:
    # ./CONSUMER-FINANCE END
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000



