server:
  port: 8000

spring:
  application:
    name: spring-cloud-eureka
#  profiles: peer1

eureka:
  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    hostname: ${spring.cloud.client.ipAddress}
    hostname: peer1
  client:
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8001/eureka/,http://${eureka.instance.hostname}:8002/eureka/
      defaultZone: http://peer2:8000/eureka/
    fetch-registry: true
    register-with-eureka: true