server:
  port: 9091
  contextPath: /authorization-agent

logging:
  level:
    org.springframework.security: DEBUG

authorization:
  manager:
      url: http://localhost:8081/authorization-manager

resourceServer:
  resourceId: authorization-agent

remoteTokenServices:
  clientId: my-trusted-client-with-secret
  clientSecret: somesecret
  checkTokenEndpointUrl: http://localhost:9090/authorization-service/oauth/check_token
  
#MYBATIS
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.fintecher.authorization.agent.entity.**

#DATASOURCE
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20