server:
  port: 8081
  contextPath: /
spring:
  output:
    ansi:
      enabled: never
  http:
    multipart:
      # 单位文件最大值
      max-file-size: 10MB
      # 单次请求的文件总数总大小
      max-request-size: 50MB
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            ##设置连接超时时间 10秒
            timeoutInMilliseconds: 10000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false