server:
  port: 8088
  contextPath: /authorization-manager

#MYBATIS
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package:  cn.fintecher.authorization.manager.userdetails.entity.**

#DATASOURCE
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.60.107:3306/supplycfdb_demo?useUnicode=true&characterEncoding=UTF-8
    username: demouser
    password: demomysql!olap
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    #当前应用名称
    name: authorization-manager

info:
  component: Authorization Manager


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false