# log
logging:
   config:
     classpath: logback-spring.xml
   path: /data/logs/sms
   
#Server
server:
  port: 8888
  context-path: /sms
  
spring:
    datasource:
        url: jdbc:mysql://172.16.10.35:3306/smsdb?characterEncoding=utf8
        username: zwuser
        password: zwusermysql!
        driverClassName: com.mysql.jdbc.Driver
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
#  	redis: 
#      timeout: 5000
#       pool:
#         max-active: 8
#         max-idle: 8
#         max-wait: -1
#         min-idle: 0
#       cluster:
#         nodes: 172.16.10.151:6379,172.16.10.152:6379,172.16.10.153:6379,172.16.10.121:6379,172.16.10.204:6379,172.16.10.205:6379 
#         max-redirects: 3
#         password: zhiwang.123
#         timeout: 5000
       
# voice message
yuntongxun:
    accountid: 560f12323352f2e49230f3d8273314eb
    autotoken: 2f13254db878f2069fd1f8a6f5d2c279
    applyid: 89eb3bb1e1d44015a5ea62db9bfc3931
    displaynum: 125909888428
    playTimes: 3

  
     